package com.likelion.asyncalign.global.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    INVALID_REQUEST(HttpStatus.BAD_REQUEST),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    CONVERSATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    MESSAGE_NOT_FOUND(HttpStatus.NOT_FOUND),
    WORKSPACE_NOT_FOUND(HttpStatus.NOT_FOUND),
    WORKSPACE_ACCESS_DENIED(HttpStatus.FORBIDDEN),
    WORKSPACE_OWNER_REQUIRED(HttpStatus.FORBIDDEN),
    WORKSPACE_ALREADY_DELETED(HttpStatus.CONFLICT),
    INVITATION_INVALID(HttpStatus.BAD_REQUEST),
    INVITATION_EXPIRED(HttpStatus.GONE),
    INVITATION_EMAIL_MISMATCH(HttpStatus.FORBIDDEN),
    INVITATION_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    EMAIL_VERIFICATION_REQUIRED(HttpStatus.BAD_REQUEST),
    INVALID_VERIFICATION_CODE(HttpStatus.BAD_REQUEST),
    VERIFICATION_CODE_EXPIRED(HttpStatus.GONE),
    VERIFICATION_RESEND_TOO_SOON(HttpStatus.TOO_MANY_REQUESTS),
    FILE_UPLOAD_FAILED(HttpStatus.BAD_REQUEST),
    ATTACHMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    ATTACHMENT_ACCESS_DENIED(HttpStatus.FORBIDDEN),
    FILE_SIZE_EXCEEDED(HttpStatus.PAYLOAD_TOO_LARGE),
    UNSUPPORTED_FILE_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    AI_REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND),
    AI_REVIEW_FAILED(HttpStatus.BAD_GATEWAY),
    AI_REVIEW_NOT_CONFIRMED(HttpStatus.CONFLICT),
    AI_REVIEW_EXPIRED(HttpStatus.GONE),
    UNDERSTANDING_CARD_NOT_FOUND(HttpStatus.NOT_FOUND),
    CARD_INVALID_STATE(HttpStatus.CONFLICT),
    CARD_RESPONSE_NOT_ALLOWED(HttpStatus.FORBIDDEN),
    REVISION_LIMIT_EXCEEDED(HttpStatus.CONFLICT),
    DIRECT_CONVERSATION_WITH_SELF(HttpStatus.BAD_REQUEST),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
